dmx_port = '/dev/cu.usbserial-6AYL2V8Z'

# midi_input_name = 'nanoKONTROL SLIDER/KNOB'

[lamp_descs]
gantom = ['gantom', 0]
laser = ['laser', 49]

[osc_desc]
endpoints = []
ip = '127.0.0.1'
port = 5005
maxsize = 0
thread_count = 1
